#ifndef SIMULATION_DECLARATIONS_H
#define SIMULATION_DECLARATIONS_H

#define CELL_SIZE 1

#define NUMBER_OF_MARKER_PARTICLES 1000

#define INITIAL_WATER_CUBE_SIZE 10
#define WATER_ARENA_SIZE 20

enum CellType_type {
	CELL_TYPE_UNSPECIFIED,
	CELL_TYPE_AIR,
	CELL_TYPE_FLUID,
	CELL_TYPE_SOLID,
};

#endif // SIMULATION_DECLARATIONS_H
